import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  courseSidebar: [
    {type: 'doc', id: 'README', label: 'Course overview'},
    {type: 'autogenerated', dirName: '.'},
  ],
  playbooksSidebar: [
    {type: 'doc', id: 'mcx_intraday_breakout_playbook', label: 'Intraday Breakout'},
  ],
};

export default sidebars;
